HISTOGRAM_BIN_WIDTH = 16
HISTOGRAM_THRESHOLD = 0.01
HISTOGRAM_BORDER_HEIGHT = 0.25
HISTOGRAM_BORDER_WIDTH = 0.33
ORDER = 3
BPS = 16

TEMPERATURE_CORRECTIONS = "curves/temperature.bin"

CONFIG = "positif.toml"

